export default {
  plusSign: '+',
  minusSign: '-',
  ok: 'Ok',
  cancelString: 'cancel',
  companyName: 'Supermart Cart',
  name: 'Name',
  password: 'Password',
  login: 'Login',
  logout: 'Logout',
  sureLogout: 'Are you sure, you want to Logout?',
  signup: 'Signup',
  enterName: 'Enter Full Name',
  enterMobileNo: 'Enter Mobile Number',
  enterEmail: 'Enter Email',
  enterPassword: 'Enter Password',
  enterConfirmPass: 'Enter Confirm Password',
  noAccount: "Don't have an Account?",
  alreadyAccount: 'Already have an Account?',
  validCred: 'Enter Valid Credentials',
  accExist: 'Account Exist',
  userNotExist: "User doesn't Exist.",
  pleaseSignup: 'Looks like user does not Exist, please Signup.',
  invalidCred: 'Invalid Credentials',
  invalidPass: 'Invalid Password',
  checkCredentials: 'Check User Credentials',
  welcome: 'Welcome!',
  search: 'Search',
  add: 'Add',
  addCart: 'Add to Cart',
  buyNow: 'Buy Now',
  alreadyInCart: 'Item already in Cart',
  totalAmount: 'Total Amount',
  highestQuantity: 'No more item Available',
  productDetails: 'Product Details',
  success: 'You have successfully ordered.',
  priceDetails: 'Price Details',
  status: 'Status',
  totalItems: 'Total Items',
  items: 'Items',
  referenceId: 'Reference ID',
  noOrders: 'No Orders Found',
  emptyCart: 'No Items Found',
  noProducts: 'No Product available...',
  productName: 'Product Name:',
  price: 'Price',
  goHome: 'Go to Home',
  wrongPassword: 'wrongPassword',
  checkout: 'Checkout',
  shopNow: 'Shop Now',
  cart: 'Cart',
};
